# Spring properties
spring:
  application:
    name: main-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.realife.services.configurations.RealNamingStrategyImpl
  datasource:
    url: jdbc:mysql://localhost/realife_development
    username: root
    password: sa123..
    driver-class-name: com.mysql.jdbc.Driver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}

# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost/realife_development
    username: root
    password: sa123..
    driver-class-name: com.mysql.jdbc.Driver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}

---

spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost/realife_development
    username: root
    password: sa123..
    driver-class-name: com.mysql.jdbc.Driver
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}

---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80